[package]
name = "eval"
version = "0.1.0"
edition = "2024"

[dependencies]
dfx = { path = "../dfx" }
dfx-macros = { path = "../dfx-macros" }

[patch.crates-io]
smtlib = { path = "../dfx/vendor/smtlib" }
